services:

  silver-web:
    container_name: silver-web
    image: nginx:1.25.4-alpine
    ports:
      - "3000:3000"
    volumes:
#      - ./../nginx/ssl:/etc/nginx/ssl
      - ./../build/web:/usr/share/nginx/html/
      - ./../nginx/nginx.conf-local:/etc/nginx/nginx.conf
    depends_on:
      - local-silver-api
      - local-db

  local-silver-api:
    container_name: local-silver-api
    image: "node:18-alpine"
    working_dir: /home/node/app
    volumes:
      - ./../../silver-api:/home/node/app/
    ports:
      - "3001:3001"
    command: "npm run start:local"
    env_file:
      - .env.dockercompose
    depends_on:
      - local-db
    restart: always

  local-db:
    container_name: local-db
    image: postgres:14.11-alpine3.19
    ports:
      - "5432:5432"
    env_file:
      - .env.dockercompose
    volumes:
      - local-db-data:/var/lib/postgresql/data/

volumes:
  local-db-data:
    name: local-db-data