// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:silverapp/env/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: Env.firebaseOptionsWeb,
    appId: '1:186537693375:web:becb5f544d1677e14d760a',
    messagingSenderId: '186537693375',
    projectId: Env.projectId,
    authDomain: '${Env.projectId}.firebaseapp.com',
    storageBucket: '${Env.projectId}.appspot.com',
    measurementId: 'G-Y2688NFN2T',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Env.firebaseOptionsAndroid,
    appId: '1:186537693375:android:fcd60c05ee6ea3484d760a',
    messagingSenderId: '186537693375',
    projectId: Env.projectId,
    storageBucket: '${Env.projectId}.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.firebaseOptionsIos,
    appId: '1:186537693375:ios:3988be5db077ff774d760a',
    messagingSenderId: '186537693375',
    projectId: Env.projectId,
    storageBucket: '${Env.projectId}.appspot.com',
    iosBundleId: 'com.example.silverapp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: Env.firebaseOptionsMacos,
    appId: '1:186537693375:ios:2ea7666a30afbbea4d760a',
    messagingSenderId: '186537693375',
    projectId: Env.projectId,
    storageBucket: '${Env.projectId}.appspot.com',
    iosBundleId: 'com.example.silverapp.RunnerTests',
  );
}
